version: 1.0.0
services:
  - mysql
ssh-keys:
  git-repo-key:
    AAAAB3NzaC1yc2EAAAADAQABAAACAQDHlBpCC7et5ee6XjLqiPIC9Eu8JQrAGikyqUWbNUBI3d/BmvRiXCK399WxHup12u9mOoYOL8CQNHIsxay5T8K3uMlr17L2kT/UYlPFjH1d2A7NkwEvp5fRbaooockHb1ctxde5MndoFkR9CvMR/RaJl4BydrQB2uvyA48pd0mgEg0DrhL+XLZz7blRYw9+F1eAHuR0NL0w6HUvUtud22M8bKoQvE/PSPKyoVQ9OGdvMqkRDmERX6P4Ngoyz0kaWGo293kXuGqa4RH+njuBNbv0guVH0pqd4QojW6XpFwQewcE9kEJVVistC/TAtElFvDiweLXL30Kjk2/GGtrfiRGtfYVnRCR1a+v2Jb+KCg20NZzgbSCHs5pn56zDqcr4Tx9j3aTwPcKpDG00PEQrPbu+EwhUNT9SVlwHGvj9gGVZ1nMJVGPJWjU16/rafXlCzgGVxLB5qJ50TyDRIQm2xLcViCcswTb4cPbv82+Y+UaPbZStcn+wVU0Yd60Scr79xIVksHRCbE2Q0886eLifxAfdmPnatdYgmXZLsHchn8uPmdx6EPDI7qS0BnQjYR25njxLPtulEPQaWVjPwumZKOl63SU25g+zYnwM4ak+ENBDS+Jbt3WWe2ylpO6FEdztTDtel4lP/OZJQNv2ZRJJl0Ft7Gz720icGRvTpgnVUkhnmQ== david.rosenbaum@Davids-MacBook-Pro.local

events:
  build:
    steps:
      -
        assemble:
          type: script
          script:
            - './assemble.sh'
      -
        compile:
          type: script
          script:
            - 'npm install less'
            - './node_modules/less/bin/lessc docroot/themes/custom/bayside_theme/less/style.less docroot/themes/custom/bayside_theme/css/style.css'
      - test:
          type: script
          script:
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 4'
            - 'cd ..'
            - ./bin/behat
      -
        post-build:
          type: script
          script:
            - 'chmod u+w docroot/sites/default/settings.php'
            - 'if [ -e "scripts/settings.php" ]; then cp scripts/settings.php docroot/sites/default/settings.php; else cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php; fi'
variables:
  global:
    EMAIL:
      secure: 2ac4WuWKqzqBaNI/LcrXyBKP17925qKAl93r+oumHK5Sxs9kh0QgoDSHiWK6Y0+gJFT2kCZ81LkS33X2TWP64kIyMKL/vzvgd/sY6Kg/Q0A5Hj4boQs01jH7sMnQGPy2MRQrhlgwFNhFJoeJaAT1CnkUDWL/q7Ej4QGASiOf9E39+zSU7bzTmZEUo6uZaqP2/fauyRqSHGnWq0VtwCy9fb3Sffv9GCofV2JN6rTE6eccl5842POf1iLf1+JSyueZtzgr/QP/jgMDbyzl8fOvlbWBEZUU6M+PUJoM9X0K6p07wGUd/GMmBVzW+GvTdQ9JuI7dxKU+t3JVGXXd62XOA84r3mhe7D8Rn1Tisi+09uS9+NoohzKgzRBqXKqgBg1t9mZVkZiQP2LqVvBA+bze00dMnYIAjn5+UZ5hQqPL1+0sHYW3cB0ARUnEW/m5p/UyzhSJ2xthLS5P+2DE6lDc4p6Daze+DLKUiqMM7Ijuw/C3xSu/quIy/lW/RFfbCu73UZDozUMluwh37qG3Y8d6fQYZ3hm34oLh2/wof+avJvzjjFd8xG5e9g5xGzgqF/CjyEt/Vjw4jeBMTM8qHOCzreAqYR6kaS7C3tXm5gLAid5lTUsd4Ode+jQg6eHMGr7sC5BWHiKpCGmGfYImSN5X5HMh9bb3HIUPrg6XKboH3/BD4U=eW72X/knUQpizhkw2iFLRLM8f6dwi7W44cBs6r96KqE=
    VALIDATION_TOKEN:
      secure: 2acuDn4IYZ3YygDO0z93wlL8EtjNE3esYNPGdCcs7v91WU/IcX2ArCslXDIpH6js4sJ67ixP1pgebGjMd2hVqFj7Xq+dT+CL5kPR3R/UGl6ESbAcf3OcnOpXQ3W9aetRE25IxSbsjIjYrjM4L8h0ASM0dsyHjjJZkPPtR2ADSaa6a+VX06vLob5uS5Pxrip5QnGiW8GGJ4xSeD7gq+CypZYx4IvHTRf2MA72DDuLDuKgCnRiyvulP6VwCRashx/Smb1An5vCtAOgqJg4ktf0yJdgzStgRgcOTqE9diB6wbT8kjlSzZBFrKVLinw6SCUx2Y/BWvZGEh7/bw+98R+sJrE1aGyP1zWGBJhF0sYAzWuYNKxGdXxTeZeuVj7XCHQe85PyjbhcQODjafluWU3utdUwi8BmWiSjA5VrQh4IvLoao1F0j/5rrB7+MJ4iTTK47Wtmet4f0C+jwxjoasntMA3m6nGOawgOg5nwAtf0Ad9PMg7q4rbxlvJPGK7Cdkw0nFfBskGaa/DVuReL8L/IkJgNwPQUaCtTU1DHV0rD2ioKxTttDRvyCwr3Fe/OXCNdgrN1eQewhyShxuqjKNglOd4eucw4OdMTOXQAn4D034Ud5vmTMQgli7PP+9EDvQwQl9zD5p6WKlTFWrEZXK4PQaxu9ExDpLq1ixwxosolBsGVUM=6Mp7SxxS9PRdjt2n+OjpCBBYcIFeULeeG4AxA9H8R0gbbXvwNvuxsspOiRhorrPN
