version: 1.0.0
services:
  - mysql
ssh-keys:
  git-repo-key:
    secure: F6NqybpNF3jcKg/gWumGsiINTW2HZZFWlaHbGnsylrjqPT5WD4RINca1bz3jzb8l
    8/yl9MlpvPRfU5u26mfJbjNzxoNOjNJEkvrCRNLy6EynnGdKptm3AqSAMDx9de08
    y9lRMbzwkIzAci0eVk5svEHBsd0q29d6wKZsINfAXlZEGRIyas0WAxwi3tIhLAcm
    sBflmkM+MVVz7ZUfbK+//rbFjrFkiRso9Y91BeWEifg11lV4SauJhBjYzXDDTQVj
    5SXyQBH1bzuzZ5qc46CbdHDoXVhF0ne+oerj/O/PXw5hex+GRhB6htFKCmSDLuke
    9lH8Gw/DOwcD1dFtxVU1h0kZNFRHvIbNaVFblVb5UeELXMGUu/MAxlcMp/LwUHbS
    X3m8esTzNFHORIB6st68m7rR0rbkaRdisRTFBNJ8rYB77jv7yDDbdgUkgdrFX7Q9
    36gEOoOfh009g+781oRWI3j7BmZ3by781XAbQ+2NSpeuRdv6ofh8+zjtEeF98ovI
    Hq0k3RlrgEhI5i0R9WF0p01q04oP9b5wqoZ05iUwu/7AhRHL4PtrgXOz+wsdOjCL
    NTF0TU49VV1NTTuqOX8okxXKCy1HLfE2++2Hf49NiHYnPJBY58apeivj+asszi2j
    GuWy88lM7sS0uvPCaxmfShaL5gnIjnNW5vtGkm0jyRkE6S51nGDOvQJLi/kvpkdg
    fxTVKu8V276sw8Lg5sltY2j2aqpiGuWTXOR1e9o0MMfxAkLTBQ9AJBgIhJ92rhhu
    mcmN71xY9yunFYpFPgzRAsfizX2oQ4cyKXoa8MC6NLo3tRPzw7UyTkeV/5toopJJ
    H9Wjzimr7uuEzFQ6aLZLCjoEUtpO1TupO2YLFJZip+eovaOv71Xx1kp5o9kM1W7Y
    Zv/m/aZ3mYHVoXLBYIArp9XmuStkPx+cvCbo0+42jXSBNI4wPzKU5ElSWPGlB2D/
    kp/jWS5wBnWwtILVLkO3/FTToDUzibi2xjKEjnS0cKcFfTswhMfU+0N+Y/q2gCjJ
    82x5bcu9I/OIuKmicliIiGZRNrF1kQO5Wm1C45/CY5AisytcljyyKbGAswdI5PUY
    HZA68SUFuy18sj5JkF9o36Ql5NjXvkIsQ2ANkf6YfkoGttSOnNfwA9lCzn/IGoDq
    1tM6vXZGX5142T/qYSRJGzfBUH7kGp6vr20JyrbsuHYJ/tsHiMFOyqQYjVE6x+98
    SqzbISUGYnAOXbMPND8ts02vNL6O3cBs08z5D3GRpTKg5BxwtrUSRLtMEecB/6bw
    i/IYJdfNE7fFkSq1HohOuA8TASX1PsOYIc3nbjP9Rto4R7mt5qf30N1d0L6hmYMW
    TjgSi+n8i9V4bIVlLgjwlF6x/ZZ1kpMyDYrjneI4pTmlqJpC12l/l36U0KAs2zuW
    vsVP+Vf3tW2KwymMLvpnDlS8HXIQX0ZNQQmwE8TJF3pNWl17pp5+DR0BYZrv4Ble
    2mdQEylg8QCwJw5Xw1oGN+xKEfdLUxe6DLYmTH4GpuLmrM0YwJsvLGC18pM3xJUl
    bpZTQmsNOTFH9Rr2MOOn9RPhWfO2971Ezqvse+eyH/oqSWl9qt85dQvGE/O+PCD/
    9dVZL664bowfLe+L4L2Uo4n6tjSOu9Mg04rYhh7p4LwIWPUZB/XN2lLnZ6BSW104
    U7nzRk1lKMJ1VgVFle1Z2uZ4Ny6FpBWvdWBLBTJ19wQyuvsYKrdE+rPQWAIa8R16
    xwTBDZDP2iOKgHf0kpHqhJNhdOIThaAwRxUTNz5bXEi8VAC5Uc4JvaYTnspqkX1C
    gJKPIR0Me9P/W1uajhAmj9YSXweI7hUJmFNg32aQgiEI8G6YIkeHQJm+A8p+YzWO
    Serx4EJMdliDvbDbEZbLrEcwGxDpwz3r2iJpxOr+C9y4gg6XBAQVddH8Sznv5qHt
    uf3sJLqT+qwImsOfioWQr0VRn6yx3qq0040ebzIfnBn1PHcUSm3P1SZYWtTm5h86
    RccCdJ1decW1cc9Y8L6QpjEEXbOQT0zSUg7HnqdVT+8FtiUaDeeAqzxeKnPGvyi6
    lzYt1zXK7NTwAFNfdV+8pbUYyl/MMaTg1ueO5m7E3rNZKIRTfTr3sJcLUnEsHDZL
    DXBT4Ejj/XPi8SLNYFxWxfNb5z5StZF+a/iLvHc29I3UXKd7bKGrp9mpm0e78+Jw
    fTrY5wl/iVABPnyuKWftG0DIoqP2bIVSn/4Y4ytDDQu6Xg6D4vAT3wyAmQPIgSsi
    ii3LsjBXZKeC0NQBnuf+uinTvM7c70ZWyn97VMkdYEZkHWjy14qs/xIfG+fr+IHd
    2BInTVzGATwfoPqX8UbCOtRL9L5SwHkP+CRtu0vkE9zB1AEqn911utJ4Aaofomvj
    Ufp2jsbF4SZE2VEBO3OzmHgNKMEwsMYvzs7i+ORjMhLAAiI60G5aXmNeEYd3vOwQ
    EqYhdS1k1SmnsqJheTxreaiUTEtaykF/UiYDsa/UjRPcU3leHJoXGnVEwu0UTyq8
    7p8lAaaKgewgcLNjTVZ+omX/lcuRciZ9YaQXq4zZcUKNRmwrMUu0lEbU2kwvnEhG
    Au0YeS+uQkWd3SUJ0zqCoIjMqYx1jeWdayNWO89pVa20X2uVjLhHOGHGqwL/0DD9
    Tigv73xaiLMF66ugtLXLQcAA3sBlldwhzj/vKq5lBt3bqNXZjPljBc+o5aPRfm/P
    c1iYoBCiWSnavg4nXfWEmszp9kmqsRNx57rjz9EFeADvuZG+rYz8CenEI6t9sP/O
    enOIJ/gWhUPtkVaaC3LUPGhbv7rAPEZQsKwg55qTr3W+k/6KBfr4rUbDSL0LUe92
    hGXR160YoPTzw8oH2DqAuWcQqtfWX3sgEZWZat7XXdE13EQOcVGvm5OQTDCOBHst
    IFuVSIeQKyoKJdEKh3ho6/YDokFDYg5kKSEx2YsH61L5/nd1OVF+u46Jwpbpbtj6
    yUjPh4STC4I1fchy8aYS4qseiHhUJTo8AlFE46h2A2XQyhQAx6dzYmR9sas21htJ
    i8fRD3BTv5AJJMOkB/v7NIamRahrR0qOzNP3vwJkeqBGX/NkRt7u/g2ZVenH2eKo
    cnEOQYM1T2WTK4dft2he51T7jJnMyKIoj9XLsNyQPuZ9EZUYOfb4cEvj09w3ft+N
events:
  build:
    steps:
      -
        assemble:
          type: script
          script:
            - './assemble.sh'
      -
        compile:
          type: script
          script:
            - 'npm install less'
            - './node_modules/less/bin/lessc docroot/themes/custom/bayside_theme/less/style.less docroot/themes/custom/bayside_theme/css/style.css'
      - test:
          type: script
          script:
            - 'mysql -u root -proot -e "CREATE DATABASE drupal"'
            - 'cd docroot'
            - '/usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../bin/drush site-install -y --db-url=mysql://root:root@127.0.0.1:3306/drupal'
            - 'php -S 127.0.0.1:8081 &'
            - 'sleep 4'
            - 'cd ..'
            - ./bin/behat
      -
        post-build:
          type: script
          script:
            - 'chmod u+w docroot/sites/default/settings.php'
            - 'if [ -e "scripts/settings.php" ]; then cp scripts/settings.php docroot/sites/default/settings.php; else cp docroot/sites/default/default.settings.php docroot/sites/default/settings.php; fi'
variables:
  global:
    EMAIL:
      secure: 2ac4WuWKqzqBaNI/LcrXyBKP17925qKAl93r+oumHK5Sxs9kh0QgoDSHiWK6Y0+gJFT2kCZ81LkS33X2TWP64kIyMKL/vzvgd/sY6Kg/Q0A5Hj4boQs01jH7sMnQGPy2MRQrhlgwFNhFJoeJaAT1CnkUDWL/q7Ej4QGASiOf9E39+zSU7bzTmZEUo6uZaqP2/fauyRqSHGnWq0VtwCy9fb3Sffv9GCofV2JN6rTE6eccl5842POf1iLf1+JSyueZtzgr/QP/jgMDbyzl8fOvlbWBEZUU6M+PUJoM9X0K6p07wGUd/GMmBVzW+GvTdQ9JuI7dxKU+t3JVGXXd62XOA84r3mhe7D8Rn1Tisi+09uS9+NoohzKgzRBqXKqgBg1t9mZVkZiQP2LqVvBA+bze00dMnYIAjn5+UZ5hQqPL1+0sHYW3cB0ARUnEW/m5p/UyzhSJ2xthLS5P+2DE6lDc4p6Daze+DLKUiqMM7Ijuw/C3xSu/quIy/lW/RFfbCu73UZDozUMluwh37qG3Y8d6fQYZ3hm34oLh2/wof+avJvzjjFd8xG5e9g5xGzgqF/CjyEt/Vjw4jeBMTM8qHOCzreAqYR6kaS7C3tXm5gLAid5lTUsd4Ode+jQg6eHMGr7sC5BWHiKpCGmGfYImSN5X5HMh9bb3HIUPrg6XKboH3/BD4U=eW72X/knUQpizhkw2iFLRLM8f6dwi7W44cBs6r96KqE=
    VALIDATION_TOKEN:
      secure: 2acuDn4IYZ3YygDO0z93wlL8EtjNE3esYNPGdCcs7v91WU/IcX2ArCslXDIpH6js4sJ67ixP1pgebGjMd2hVqFj7Xq+dT+CL5kPR3R/UGl6ESbAcf3OcnOpXQ3W9aetRE25IxSbsjIjYrjM4L8h0ASM0dsyHjjJZkPPtR2ADSaa6a+VX06vLob5uS5Pxrip5QnGiW8GGJ4xSeD7gq+CypZYx4IvHTRf2MA72DDuLDuKgCnRiyvulP6VwCRashx/Smb1An5vCtAOgqJg4ktf0yJdgzStgRgcOTqE9diB6wbT8kjlSzZBFrKVLinw6SCUx2Y/BWvZGEh7/bw+98R+sJrE1aGyP1zWGBJhF0sYAzWuYNKxGdXxTeZeuVj7XCHQe85PyjbhcQODjafluWU3utdUwi8BmWiSjA5VrQh4IvLoao1F0j/5rrB7+MJ4iTTK47Wtmet4f0C+jwxjoasntMA3m6nGOawgOg5nwAtf0Ad9PMg7q4rbxlvJPGK7Cdkw0nFfBskGaa/DVuReL8L/IkJgNwPQUaCtTU1DHV0rD2ioKxTttDRvyCwr3Fe/OXCNdgrN1eQewhyShxuqjKNglOd4eucw4OdMTOXQAn4D034Ud5vmTMQgli7PP+9EDvQwQl9zD5p6WKlTFWrEZXK4PQaxu9ExDpLq1ixwxosolBsGVUM=6Mp7SxxS9PRdjt2n+OjpCBBYcIFeULeeG4AxA9H8R0gbbXvwNvuxsspOiRhorrPN
